site_name: jiao web home
theme:
  name: material
  icon:
    repo: fontawesome/brands/gitlab
  palette:
    primary: green
  language: zh
repo_url: https://github.com/jiaojiao314/jiao_web
markdown_extensions:
  - toc:
      permalink: true
